# Generated by Django 6.1 on 2026-09-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agroquimicos',
            fields=[
                ('ID_Agroquimico', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_agroquimico', models.CharField(max_length=60)),
                ('Descripcion_agroquimico', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agroquímicos',
                'db_table': 'AGROQUIMICOS',
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('ID_Perfil', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_perfil', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'db_table': 'PERFILES',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=50)),
                ('Descripcion_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('ID_Proveedor', models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Proveedor')),
                ('telefono_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email_proveedor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion_proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('estado_proveedor', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDORES',
            },
        ),
        migrations.CreateModel(
            name='TiposMovimientos',
            fields=[
                ('ID_Tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_tipo_movimiento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'TIPOS_MOVIMIENTOS',
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('ID_Tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_tipo_producto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'TIPOS_PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='ProductosXAgroquimicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Agroquimico', models.ForeignKey(db_column='ID_Agroquimico', on_delete=django.db.models.deletion.CASCADE, to='inventario.agroquimicos')),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'verbose_name_plural': 'Productos por Agroquímicos',
                'db_table': 'PRODUCTOS_X_AGROQUIMICOS',
                'unique_together': {('ID_Producto', 'ID_Agroquimico')},
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='agroquimicos',
            field=models.ManyToManyField(through='inventario.ProductosXAgroquimicos', to='inventario.agroquimicos'),
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('ID_Proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Productos por Proveedores',
                'db_table': 'PRODUCTOS_X_PROVEEDORES',
                'unique_together': {('ID_Producto', 'ID_Proveedor')},
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedores',
            field=models.ManyToManyField(through='inventario.ProductosXProveedores', to='inventario.proveedores'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ID_Stock', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_stock', models.IntegerField()),
                ('Stock_minimo', models.IntegerField()),
                ('ID_Producto', models.OneToOneField(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'db_table': 'STOCK',
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('ID_Alerta', models.AutoField(primary_key=True, serialize=False)),
                ('Mensaje', models.CharField(max_length=255)),
                ('Fecha_hora_alerta', models.DateTimeField(auto_now_add=True)),
                ('ID_Stock', models.ForeignKey(db_column='ID_Stock', on_delete=django.db.models.deletion.CASCADE, to='inventario.stock')),
            ],
            options={
                'verbose_name_plural': 'Alertas',
                'db_table': 'ALERTAS',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='ID_Tipo_producto',
            field=models.ForeignKey(db_column='ID_Tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposproductos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.IntegerField()),
                ('Apellido_usuario', models.CharField(max_length=50)),
                ('Nombre_usuario', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(db_column='Contraseña', max_length=255)),
                ('Email_usuario', models.EmailField(max_length=100)),
                ('Estado_usuario', models.BooleanField(default=True)),
                ('Fecha_ultima_modificacion', models.DateField(auto_now=True)),
                ('Fecha_Baja', models.DateField(blank=True, null=True)),
                ('Cambiar_contrasena', models.BooleanField(db_column='Cambiar_contraseña', default=False)),
                ('ID_Perfil', models.ForeignKey(db_column='ID_Perfil', on_delete=django.db.models.deletion.PROTECT, to='inventario.perfiles')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIOS',
            },
        ),
        migrations.CreateModel(
            name='MovimientosStock',
            fields=[
                ('ID_Movimiento_stock', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_hora_movimiento', models.DateTimeField(auto_now_add=True)),
                ('Cantidad', models.IntegerField()),
                ('ID_Stock', models.ForeignKey(db_column='ID_Stock', on_delete=django.db.models.deletion.CASCADE, to='inventario.stock')),
                ('ID_Tipo_movimiento', models.ForeignKey(db_column='ID_Tipo_movimiento', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposmovimientos')),
                ('ID_Usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='inventario.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'MOVIMIENTOS_STOCK',
            },
        ),
    ]
