# Generated by Django 6.1 on 2026-10-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('ID_Perfil', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_perfil', models.CharField(max_length=50)),
                ('Estado_perfil', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'db_table': 'PERFILES',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('ID_Permiso', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_permiso', models.CharField(max_length=100)),
                ('Descripcion_permiso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Permisos',
                'db_table': 'PERMISOS',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(blank=True, max_length=50, null=True)),
                ('Nombre_producto', models.CharField(max_length=50)),
                ('Descripcion_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cantidad_presentacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Unidad_medida_producto', models.CharField(blank=True, max_length=20, null=True)),
                ('Estado_producto', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('ID_Proveedor', models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Proveedor')),
                ('telefono_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email_proveedor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion_proveedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('estado_proveedor', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDORES',
            },
        ),
        migrations.CreateModel(
            name='TiposMovimientos',
            fields=[
                ('ID_Tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_tipo_movimiento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'TIPOS_MOVIMIENTOS',
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('ID_Tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_tipo_producto', models.CharField(max_length=50)),
                ('Estado_tipo_producto', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'TIPOS_PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='PerfilesXPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Perfil', models.ForeignKey(db_column='ID_Perfil', on_delete=django.db.models.deletion.CASCADE, to='inventario.perfiles')),
                ('ID_Permiso', models.ForeignKey(db_column='ID_Permiso', on_delete=django.db.models.deletion.CASCADE, to='inventario.permisos')),
            ],
            options={
                'verbose_name_plural': 'Perfiles por Permisos',
                'db_table': 'PERFILES_X_PERMISOS',
                'unique_together': {('ID_Perfil', 'ID_Permiso')},
            },
        ),
        migrations.AddField(
            model_name='perfiles',
            name='permisos',
            field=models.ManyToManyField(related_name='perfiles', through='inventario.PerfilesXPermisos', to='inventario.permisos'),
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('ID_Lote', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_lote', models.CharField(max_length=50)),
                ('Cantidad_ingresada', models.IntegerField()),
                ('Cantidad_actual', models.IntegerField()),
                ('Fecha_ingreso', models.DateField()),
                ('Fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.productos')),
                ('ID_Proveedor', models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Lotes',
                'db_table': 'LOTES',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ID_Stock', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_stock', models.IntegerField()),
                ('Stock_minimo', models.IntegerField()),
                ('ID_Producto', models.OneToOneField(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventario.productos')),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'db_table': 'STOCK',
            },
        ),
        migrations.CreateModel(
            name='Subtipos',
            fields=[
                ('ID_Subtipo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_subtipo', models.CharField(max_length=50)),
                ('Estado_subtipo', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('ID_Tipo_producto', models.ForeignKey(db_column='ID_Tipo_producto', on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='inventario.tiposproductos')),
            ],
            options={
                'verbose_name_plural': 'Subtipos',
                'db_table': 'SUBTIPOS',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='ID_Tipo_producto',
            field=models.ForeignKey(db_column='ID_Tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposproductos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.IntegerField(unique=True)),
                ('Apellido_usuario', models.CharField(max_length=50)),
                ('Nombre_usuario', models.CharField(max_length=50)),
                ('Usuario', models.CharField(max_length=50, unique=True)),
                ('Contrasena', models.CharField(db_column='Contraseña', max_length=255)),
                ('Email_usuario', models.EmailField(max_length=100)),
                ('Estado_usuario', models.BooleanField(default=True)),
                ('Fecha_ultima_modificacion', models.DateField(auto_now=True)),
                ('Fecha_Baja', models.DateField(blank=True, null=True)),
                ('Cambiar_contrasena', models.BooleanField(db_column='Cambiar_contraseña', default=False)),
                ('ID_Perfil', models.ForeignKey(db_column='ID_Perfil', on_delete=django.db.models.deletion.PROTECT, to='inventario.perfiles')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIOS',
            },
        ),
        migrations.CreateModel(
            name='MovimientosStock',
            fields=[
                ('ID_Movimiento_stock', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_hora_movimiento', models.DateTimeField(auto_now_add=True)),
                ('Cantidad_movimiento_stock', models.IntegerField()),
                ('Observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_Lote', models.ForeignKey(blank=True, db_column='ID_Lote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lotes')),
                ('ID_Tipo_movimiento', models.ForeignKey(db_column='ID_Tipo_movimiento', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposmovimientos')),
                ('ID_Usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, to='inventario.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'MOVIMIENTOS_STOCK',
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('ID_Historial_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_alerta', models.CharField(max_length=50)),
                ('Mensaje', models.CharField(max_length=255)),
                ('Fecha_hora_historial_alerta', models.DateTimeField(auto_now_add=True)),
                ('Cantidad_al_generar', models.IntegerField(blank=True, null=True)),
                ('Stock_minimo_al_generar', models.IntegerField(blank=True, null=True)),
                ('Atendida', models.BooleanField(default=False)),
                ('Fecha_hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('ID_Lote', models.ForeignKey(blank=True, db_column='ID_Lote', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.lotes')),
                ('ID_Stock', models.ForeignKey(db_column='ID_Stock', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.stock')),
                ('ID_Usuario', models.ForeignKey(blank=True, db_column='ID_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to='inventario.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Historial de alertas',
                'db_table': 'HISTORIAL_ALERTAS',
            },
        ),
    ]
