# Generated by Django 6.1 on 2026-08-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruposQuimicos',
            fields=[
                ('ID_Grupo_quimico', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_grupo_quimico', models.CharField(max_length=60)),
                ('Descripcion_grupo_quimico', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos Químicos',
                'db_table': 'GRUPOS_QUIMICOS',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=50)),
                ('Descripcion_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('ID_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_proveedor', models.CharField(max_length=50)),
                ('Telefono_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('Direccion_proveedor', models.CharField(blank=True, max_length=30, null=True)),
                ('Email_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado_proveedor', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'PROVEEDORES',
            },
        ),
        migrations.CreateModel(
            name='TiposEmpleados',
            fields=[
                ('ID_Tipo_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_tipo_empleado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Empleados',
                'db_table': 'TIPOS_EMPLEADOS',
            },
        ),
        migrations.CreateModel(
            name='TiposMovimientos',
            fields=[
                ('ID_Tipo_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_tipo_movimiento', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'TIPOS_MOVIMIENTOS',
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('ID_Tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'TIPOS_PRODUCTOS',
            },
        ),
        migrations.CreateModel(
            name='ProductosXGruposQuimicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Grupo_quimico', models.ForeignKey(db_column='ID_Grupo_quimico', on_delete=django.db.models.deletion.CASCADE, to='inventario.gruposquimicos')),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'verbose_name_plural': 'Productos por Grupos Químicos',
                'db_table': 'PRODUCTOS_X_GRUPOS_QUIMICOS',
                'unique_together': {('ID_Producto', 'ID_Grupo_quimico')},
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='grupos_quimicos',
            field=models.ManyToManyField(through='inventario.ProductosXGruposQuimicos', to='inventario.gruposquimicos'),
        ),
        migrations.CreateModel(
            name='ProductosXProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('ID_Proveedor', models.ForeignKey(db_column='ID_Proveedores', on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
            options={
                'verbose_name_plural': 'Productos por Proveedores',
                'db_table': 'PRODUCTOS_X_PROVEEDORES',
                'unique_together': {('ID_Producto', 'ID_Proveedor')},
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedores',
            field=models.ManyToManyField(through='inventario.ProductosXProveedores', to='inventario.proveedores'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ID_Stock', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_stock', models.IntegerField()),
                ('Stock_minimo', models.IntegerField()),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'db_table': 'STOCK',
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('ID_Alerta', models.AutoField(primary_key=True, serialize=False)),
                ('Mensaje', models.CharField(max_length=255)),
                ('Fecha_hora_alerta', models.DateTimeField(auto_now_add=True)),
                ('ID_Stock', models.ForeignKey(db_column='ID_Stock', on_delete=django.db.models.deletion.CASCADE, to='inventario.stock')),
            ],
            options={
                'verbose_name_plural': 'Alertas',
                'db_table': 'ALERTAS',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('ID_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_empleado', models.CharField(max_length=50)),
                ('Apellido_empleado', models.CharField(max_length=50)),
                ('Telefono_empleado', models.CharField(blank=True, max_length=20, null=True)),
                ('Email_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('ID_Tipo_empleado', models.ForeignKey(db_column='ID_Tipo_empleado', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposempleados')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'EMPLEADOS',
            },
        ),
        migrations.CreateModel(
            name='MovimientosStock',
            fields=[
                ('ID_Movimiento_stock', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_hora_movimiento', models.DateTimeField(auto_now_add=True)),
                ('Cantidad', models.IntegerField()),
                ('ID_Empleado', models.ForeignKey(db_column='ID_Empleado', on_delete=django.db.models.deletion.CASCADE, to='inventario.empleados')),
                ('ID_Stock', models.ForeignKey(db_column='ID_Stock', on_delete=django.db.models.deletion.CASCADE, to='inventario.stock')),
                ('ID_Tipo_movimiento', models.ForeignKey(db_column='ID_Tipo_movimiento', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposmovimientos')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'MOVIMIENTOS_STOCK',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='ID_Tipo_producto',
            field=models.ForeignKey(db_column='ID_Tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.tiposproductos'),
        ),
    ]
