# Generated by Django 6.1 on 2026-09-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('ID_Permiso', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_permiso', models.CharField(max_length=100)),
                ('Descripcion_permiso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Permisos',
                'db_table': 'PERMISOS',
            },
        ),
        migrations.CreateModel(
            name='PerfilesXPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Perfil', models.ForeignKey(db_column='ID_Perfil', on_delete=django.db.models.deletion.CASCADE, to='inventario.perfiles')),
                ('ID_Permiso', models.ForeignKey(db_column='ID_Permiso', on_delete=django.db.models.deletion.CASCADE, to='inventario.permisos')),
            ],
            options={
                'verbose_name_plural': 'Perfiles por Permisos',
                'db_table': 'PERFILES_X_PERMISOS',
                'unique_together': {('ID_Perfil', 'ID_Permiso')},
            },
        ),
        migrations.AddField(
            model_name='perfiles',
            name='permisos',
            field=models.ManyToManyField(related_name='perfiles', through='inventario.PerfilesXPermisos', to='inventario.permisos'),
        ),
    ]
