# Generated by Django 6.1 on 2026-08-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertas',
            options={'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='gruposquimicos',
            options={'verbose_name_plural': 'Grupos Químicos'},
        ),
        migrations.AlterModelOptions(
            name='movimientosstock',
            options={'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productosxgruposquimicos',
            options={'verbose_name_plural': 'Productos por Grupos Químicos'},
        ),
        migrations.AlterModelOptions(
            name='productosxproveedores',
            options={'verbose_name_plural': 'Productos por Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='tiposempleados',
            options={'verbose_name_plural': 'Tipos de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='tiposmovimientos',
            options={'verbose_name_plural': 'Tipos de Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tiposproductos',
            options={'verbose_name_plural': 'Tipos de Productos'},
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='telefono',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='direccion_proveedor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='email_proveedor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='estado_proveedor',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='nombre_proveedor',
            field=models.CharField(default='Proveedor Sin Nombre', max_length=150, unique=True, verbose_name='Nombre del Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
    ]
