# Generated by Django 6.1 on 2026-08-25 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertas',
            options={'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='gruposquimicos',
            options={'verbose_name_plural': 'Grupos Químicos'},
        ),
        migrations.AlterModelOptions(
            name='movimientosstock',
            options={'verbose_name_plural': 'Movimientos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productosxgruposquimicos',
            options={'verbose_name_plural': 'Productos por Grupos Químicos'},
        ),
        migrations.AlterModelOptions(
            name='productosxproveedores',
            options={'verbose_name_plural': 'Productos por Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='tiposempleados',
            options={'verbose_name_plural': 'Tipos de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='tiposmovimientos',
            options={'verbose_name_plural': 'Tipos de Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='tiposproductos',
            options={'verbose_name_plural': 'Tipos de Productos'},
        ),
    ]
