# Generated by Django 6.1 on 2026-08-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedores',
            table='PROVEEDORES',
        ),
    ]
