# Generated by Django 6.1 on 2026-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtipos',
            name='Descripcion_subtipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
