# Generated by Django 6.1 on 2026-08-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_proveedores_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='id',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='ID_Proveedor',
            field=models.AutoField(db_column='ID_Proveedor', primary_key=True, serialize=False),
        ),
    ]
