# Generated by Django 6.1 on 2026-10-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_subtipos_descripcion_subtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertas',
            name='ID_Lote',
        ),
        migrations.AddField(
            model_name='productos',
            name='ID_Subtipo',
            field=models.ForeignKey(blank=True, db_column='ID_Subtipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.subtipos'),
        ),
    ]
