# Generated by Django 6.1 on 2026-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_permisos_perfilesxpermisos_perfiles_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Estado_producto',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='DNI',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
