# Generated by Django 6.1 on 2026-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_productos_estado_producto_alter_usuarios_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Estado_producto',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=20),
        ),
    ]
