# Generated by Django 6.1 on 2026-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_alertas_id_lote_productos_id_subtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='Estado_lote',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10),
        ),
    ]
