# Generated by Django 6.1 on 2026-09-01 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_proveedores_id_proveedores_id_proveedor'),
    ]

    operations = [
        migrations.RenameModel(
           old_name='GruposQuimicos',
           new_name='Agroquimicos',
),
        migrations.RemoveField(
            model_name='productos',
            name='grupos_quimicos',
        ),
        migrations.AlterModelOptions(
            name='agroquimicos',
            options={'verbose_name_plural': 'Agroquímicos'},
        ),
        migrations.RenameField(
            model_name='agroquimicos',
            old_name='Descripcion_grupo_quimico',
            new_name='Descripcion_agroquimico',
        ),
        migrations.RenameField(
            model_name='agroquimicos',
            old_name='ID_Grupo_quimico',
            new_name='ID_Agroquimico',
        ),
        migrations.RenameField(
            model_name='agroquimicos',
            old_name='Nombre_grupo_quimico',
            new_name='Nombre_agroquimico',
        ),
        migrations.RenameField(
            model_name='tiposproductos',
            old_name='Nombre_producto',
            new_name='Nombre_tipo_producto',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Email_empleado',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productosxproveedores',
            name='ID_Proveedor',
            field=models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ID_Producto',
            field=models.OneToOneField(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos'),
        ),
        migrations.AlterModelTable(
            name='agroquimicos',
            table='AGROQUIMICOS',
        ),
        migrations.CreateModel(
            name='ProductosXAgroquimicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Agroquimico', models.ForeignKey(db_column='ID_Agroquimico', on_delete=django.db.models.deletion.CASCADE, to='inventario.agroquimicos')),
                ('ID_Producto', models.ForeignKey(db_column='ID_Producto', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
            options={
                'verbose_name_plural': 'Productos por Agroquímicos',
                'db_table': 'PRODUCTOS_X_AGROQUIMICOS',
                'unique_together': {('ID_Producto', 'ID_Agroquimico')},
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='agroquimicos',
            field=models.ManyToManyField(through='inventario.ProductosXAgroquimicos', to='inventario.agroquimicos'),
        ),
        migrations.DeleteModel(
            name='ProductosXGruposQuimicos',
        ),
    ]
