# Generated by Django 6.1 on 2026-09-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_productos_estado_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertas',
            options={'verbose_name_plural': 'Historial de Alertas'},
        ),
        migrations.RenameField(
            model_name='alertas',
            old_name='Fecha_hora_alerta',
            new_name='Fecha_hora_historial_alerta',
        ),
        migrations.RenameField(
            model_name='alertas',
            old_name='ID_Alerta',
            new_name='ID_Historial_alerta',
        ),
        migrations.AddField(
            model_name='alertas',
            name='Tipo_alerta',
            field=models.CharField(default='Stock mínimo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiposproductos',
            name='Estado_tipo_producto',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True),
        ),
        migrations.AlterModelTable(
            name='alertas',
            table='HISTORIAL_ALERTAS',
        ),
    ]
