# Generated by Django 6.1 on 2026-10-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_lotes_estado_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='Fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
