# Generated by Django 6.1 on 2026-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_alertas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiles',
            name='Estado_perfil',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True),
        ),
    ]
