# Generated by Django 6.1 on 2026-10-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_lotes_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='ID_Subtipo',
        ),
    ]
