# Generated by Django 6.1 on 2026-10-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_perfiles_estado_perfil'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='productos',
                    name='agroquimicos',
                ),
                migrations.RemoveField(
                    model_name='productosxagroquimicos',
                    name='ID_Agroquimico',
                ),
            ],
        ),

        migrations.RemoveField(
            model_name='productosxagroquimicos',
            name='ID_Producto',
        ),

        migrations.RemoveField(
            model_name='productosxproveedores',
            name='ID_Producto',
        ),

        migrations.RemoveField(
            model_name='productosxproveedores',
            name='ID_Proveedor',
        ),

        migrations.RemoveField(
            model_name='productos',
            name='proveedores',
        ),

        migrations.AlterModelOptions(
            name='alertas',
            options={'verbose_name_plural': 'Historial de alertas'},
        ),

        migrations.RenameField(
            model_name='movimientosstock',
            old_name='Cantidad',
            new_name='Cantidad_movimiento_stock',
        ),

        migrations.RemoveField(
            model_name='movimientosstock',
            name='ID_Stock',
        ),

        migrations.RemoveField(
            model_name='productos',
            name='Fecha_vencimiento',
        ),

        migrations.AddField(
            model_name='alertas',
            name='Atendida',
            field=models.BooleanField(default=False),
        ),

        migrations.AddField(
            model_name='alertas',
            name='Cantidad_al_generar',
            field=models.IntegerField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='alertas',
            name='Fecha_hora_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='alertas',
            name='ID_Usuario',
            field=models.ForeignKey(
                blank=True,
                db_column='ID_Usuario',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='alertas_atendidas',
                to='inventario.usuarios'
            ),
        ),

        migrations.AddField(
            model_name='alertas',
            name='Stock_minimo_al_generar',
            field=models.IntegerField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name='movimientosstock',
            name='Observaciones',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='productos',
            name='Cantidad_presentacion',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='productos',
            name='Marca',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='productos',
            name='Unidad_medida_producto',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True
            ),
        ),

        migrations.AlterField(
            model_name='alertas',
            name='ID_Stock',
            field=models.ForeignKey(
                db_column='ID_Stock',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='alertas',
                to='inventario.stock'
            ),
        ),

        migrations.AlterField(
            model_name='productos',
            name='Estado_producto',
            field=models.CharField(
                choices=[
                    ('Activo', 'Activo'),
                    ('Inactivo', 'Inactivo')
                ],
                default='Activo',
                max_length=10
            ),
        ),

        migrations.AlterField(
            model_name='stock',
            name='ID_Producto',
            field=models.OneToOneField(
                db_column='ID_Producto',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stock',
                to='inventario.productos'
            ),
        ),

        migrations.CreateModel(
            name='Lotes',
            fields=[
                (
                    'ID_Lote',
                    models.AutoField(
                        primary_key=True,
                        serialize=False
                    )
                ),
                (
                    'Numero_lote',
                    models.CharField(max_length=50)
                ),
                (
                    'Cantidad_ingresada',
                    models.IntegerField()
                ),
                (
                    'Cantidad_actual',
                    models.IntegerField()
                ),
                (
                    'Fecha_ingreso',
                    models.DateField()
                ),
                (
                    'Fecha_vencimiento',
                    models.DateField(
                        blank=True,
                        null=True
                    )
                ),
                (
                    'ID_Producto',
                    models.ForeignKey(
                        db_column='ID_Producto',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lotes',
                        to='inventario.productos'
                    )
                ),
                (
                    'ID_Proveedor',
                    models.ForeignKey(
                        db_column='ID_Proveedor',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='lotes',
                        to='inventario.proveedores'
                    )
                ),
            ],
            options={
                'verbose_name_plural': 'Lotes',
                'db_table': 'LOTES',
            },
        ),

        migrations.AddField(
            model_name='alertas',
            name='ID_Lote',
            field=models.ForeignKey(
                blank=True,
                db_column='ID_Lote',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='alertas',
                to='inventario.lotes'
            ),
        ),

        migrations.AddField(
            model_name='movimientosstock',
            name='ID_Lote',
            field=models.ForeignKey(
                blank=True,
                db_column='ID_Lote',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='movimientos',
                to='inventario.lotes'
            ),
        ),

        migrations.CreateModel(
            name='Subtipos',
            fields=[
                (
                    'ID_Subtipo',
                    models.AutoField(
                        primary_key=True,
                        serialize=False
                    )
                ),
                (
                    'Nombre_subtipo',
                    models.CharField(max_length=50)
                ),
                (
                    'Estado_subtipo',
                    models.BooleanField(
                        choices=[
                            (True, 'Activo'),
                            (False, 'Inactivo')
                        ],
                        default=True
                    )
                ),
                (
                    'ID_Tipo_producto',
                    models.ForeignKey(
                        db_column='ID_Tipo_producto',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subtipos',
                        to='inventario.tiposproductos'
                    )
                ),
            ],
            options={
                'verbose_name_plural': 'Subtipos',
                'db_table': 'SUBTIPOS',
            },
        ),

        migrations.DeleteModel(
            name='Agroquimicos',
        ),

        migrations.DeleteModel(
            name='ProductosXAgroquimicos',
        ),

        migrations.DeleteModel(
            name='ProductosXProveedores',
        ),
    ]