# Generated by Django 6.1 on 2026-10-10 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_productos_id_subtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='ID_Subtipo',
            field=models.ForeignKey(blank=True, db_column='ID_Subtipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.subtipos'),
        ),
    ]
