# Generated by Django 6.1 on 2026-10-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_productos_agroquimicos_and_more'),
    ]

    operations = [

        # La columna ID_Stock ya no existe físicamente
        # en la tabla MOVIMIENTOS_STOCK.
        # Solo actualizamos el estado de Django.

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='movimientosstock',
                    name='ID_Stock',
                ),
            ],
        ),

        # La columna Fecha_vencimiento ya no existe físicamente
        # en la tabla PRODUCTOS.
        # Solo actualizamos el estado de Django.

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='productos',
                    name='Fecha_vencimiento',
                ),
            ],
        ),
    ]