version: '3.8'

services:
  db:
    image: mysql:latest  # <-- Cambiado a latest (instala la versión 8.4+)
    container_name: mysql_bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_proyecto_db
      MYSQL_USER: usuario_django
      MYSQL_PASSWORD: django_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data: